### ISSUE TITLE
ZkVM checklist

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#59]
This is a tracking issue for ZkVM implementation.

- [x] vm: Predicate tree: disjunction and program commitment: https://github.com/interstellar/zkvm/pull/4
- [x] vm: aggregated signature protocol: https://github.com/interstellar/zkvm/pull/4, https://github.com/interstellar/zkvm/pull/8
- [x] vm: batched verification of point operations: https://github.com/interstellar/zkvm/pull/16
- [x] vm: VM state with basic input+signtx+cloak+output flow: https://github.com/interstellar/zkvm/pull/4
- [x] vm: encoding inputs/outputs: https://github.com/interstellar/zkvm/pull/4
- [x] vm: merkle tree for txid: https://github.com/interstellar/zkvm/pull/4
- [x] api: prover: low-level API: convert a stream of `Instruction`s into a program bytecode, tx sig and r1cs proof. PR: #69, #79
- [x] api: unit tests for end-to-end tx creation/verification using low-level API: https://github.com/interstellar/slingshot/pull/100
- [ ] api: prover: high-level input-output txbuilder on top of the low-level API.
- [ ] api: prover: issuance txbuilder: add optional nonce if no inputs are present
- [ ] api: prover: retirement (add an API for destroying a value)
- [ ] api: prover: make txid-inclusion proof for chosen outputs
- [ ] vm: `left`/`right` instructions
- [ ] vm: `delegate`/`call` instructions
- [ ] vm: `contract` instruction
- [x] vm: `log` instruction https://github.com/interstellar/zkvm/pull/20
- [ ] api: txbuilder: add data-only (`log`) entry API
- [ ] api: payment channel protocol
- [ ] api: vault protocol
- [ ] vm: `mintime`/`maxtime` instructions
- [ ] vm: `qty`/`flavor` instructions
- [ ] vm: `var`/`const` instructions
- [x] vm: `neg`/`add`/`mul` instructions: https://github.com/interstellar/slingshot/pull/88, https://github.com/interstellar/slingshot/pull/101, https://github.com/interstellar/slingshot/pull/102
- [x] vm: `eq`/`and`/`or`/`verify` instructions: https://github.com/interstellar/slingshot/pull/102, https://github.com/interstellar/slingshot/pull/147
- [ ] vm: `alloc` instruction
- [ ] vm: `import`/`export` instructions
- [ ] vm: `blind`/`reblind`/`unblind` instructions

**Comment by oleganza** [comment]
The list of all issues is now much more up to date and provides a view of the pipeline, so i'm closing this tracking issue.
